repos:
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
        args: [--extend-exclude="(.*misc.*/.*.py|.*config.*/.*.py|.*config.*.py|docs/source/.*.py|utils/.*.py|setup.py)"]