version: 2

python:
      version: "3.9"
            install:
                    - method: pip
                            path: .
                            sphinx:
                                  fail_on_warning: true
