name: ci

on:
  push:
    branches: [ maly_test_ci ]
  pull_request:
    branches: [ main ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - uses: pre-commit/action@v3.0.0
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Pythium and dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install .[tests]
    # - name: Static code analysis with flake8
    #   run: |
    #     # stop the build if there are Python syntax errors or undefined names
    #     # https://michaelcurrin.github.io/dev-cheatsheets/cheatsheets/python/linting/flake8.html
    #     flake8 src/pythium --select=E9,F63,F7,F82 --show-source
    #     # check for additional issues flagged by flake8
    #     flake8
    # - name: Format with Black
    #   run: |
    #     black --check --diff --verbose .
    - name: Run example
      run: |
        python utils/create_parquet.py
    - name: Test with pytest and generate coverage report
      if: matrix.python-version == '3.7'
      run: |
        pytest --runslow --cov-report=xml
    - name: Test with pytest
      if: matrix.python-version != '3.7'
      run: |
        pytest --runslow
    - name: Upload coverage to codecov
      if: matrix.python-version == '3.7'
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        name: codecov-umbrella
        fail_ci_if_error: true
    - name: Build docs with sphinx
      run: |
        python -m pip install .[docs]
        sphinx-build -W docs docs/_build